### ISSUE TITLE
[PostGIS] helm install fails for v0.2.2

### ISSUE THREAD

**Issue by daveekr** [kartoza/charts#34] opened 2021-03-11 10:37 UTC
Hello,

I wanted to install the latest PostGIS chart via `helm install pgis kartoza/postgis`. Doing so failed with following message

> Error: parse error at (postgis/templates/tests/postgres-connection.yaml:37): unclosed action

When falling back to version 0.2.1 the installation succeeded.

My system:
macOSX 10.14.6
Docker Desktop 3.10.0
Kubernetes 1.19.3
Helm 3.4.1

**Comment by lucernae** [comment] 2021-06-11 11:34
@daveekr thank you for your report.
We figured out that is caused by the golang template syntax unsupported for earlier version of Helm, so we had to use the old syntax. We will release the fix in 0.2.4.

**Comment by lucernae** [comment] 2021-06-11 11:37
To be precise, the particular issue is fixed in v0.2.3 via this PR #35, but that version also failed to upgrade inplace (v0.2.3 to v0.2.3 to change parameters). So we are looking to fix that too in v0.2.4.

**Closed** 2021-06-20 13:24 UTC
